apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storagebucket-azure
  labels:
    provider: azure
    crossplane.io/xrd: storagebuckets.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: StorageBucket
  
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # Resource Group
          - name: resource-group
            base:
              apiVersion: azure.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                forProvider:
                  location: eastus
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "rg-%s"
          
          # Storage Account
          - name: storage-account
            base:
              apiVersion: storage.azure.upbound.io/v1beta2
              kind: Account
              spec:
                forProvider:
                  accountTier: Standard
                  accountReplicationType: LRS
                  location: eastus
                  tags:
                    managed-by: crossplane
                providerConfigRef:
                  name: default
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.location
              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.tags.environment
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Replace
                      replace:
                        search: "-"
                        replace: ""
                  - type: string
                    string:
                      type: Format
                      fmt: "stx99%s"
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/claim-name]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.resourceGroupName
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "rg-%s"
              # Mapear storageClass para accountTier
              - type: FromCompositeFieldPath
                fromFieldPath: spec.storageClass
                toFieldPath: spec.forProvider.accountTier
                transforms:
                  - type: map
                    map:
                      standard: Standard
                      premium: Premium