apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-crossplane-random
  namespace: crossplane-system
spec:
  forProvider:
    location: eastus
  providerConfigRef:
    name: default